services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    volumes:
      - ./frontend/uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_URL=http://backend:5000
      - SECRET_KEY=${SECRET_KEY}
      - NEXT_PUBLIC_USE_CLERK=${NEXT_PUBLIC_USE_CLERK}
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./frontend/uploads:/app/uploads
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - SECRET_KEY=${SECRET_KEY}

volumes:
  photos:
